### PR TITLE
PR : Our Team Page 

### PR DESCRIPTION
**Pull request by SivaaB**
Changes: 

1) Our Team Page: Photos, and relevant links for Email, GitHub, and LinkedIn have been uploaded. 
2) Have changed the center text on the home page (testimonial type section to say) --> "Hear from our members!".

### CODE REVIEW

**Comment by Krish054** [comment]
@SivaaB There's a spelling error in Aman's name

**Comment by anuragkj** [comment]
You have a merge conflict in package.json. Please resolve and fix Aman's name and send another pull request

**Review by anuragkj — CHANGES_REQUESTED** [review]
You have a merge conflict in package.json. Please resolve and fix Aman's name and send another pull request

**Comment by SivaaB** [comment]
@Morpheus054 ty for pointing it out, will fix. 
@anuragkj okau gotchu.

**Pull request closed without merging**
